name: Test-2

on:
  # push:
  #   branches: 
  #   - develop
  #   - master
  # pull_request:
  #   branches:
  #   - master
  #   - develop

  workflow_dispatch:

concurrency: 
  group: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run --name duckling --rm -v $PWD:/host rasa/duckling cp /usr/local/bin/duckling-example-exe /host/
          duckling-example-exe -p 8000 &
          curl -XPOST http://localhost:8000/parse --data 'locale=en_GB&text=tomorrow at eight'